### ISSUE TITLE
'Custom element doesn't exist: xiaomi-vacuum-card' in Home Assistant IOS app

### ISSUE THREAD

**Issue by CarpeDiemRo** [benct/lovelace-xiaomi-vacuum-card#10]
The custom card works fine in Chrome(WIN10) and Safari(macOS) but on the Home Assistant app form IOS displays 'Custom element doesn't exist: xiaomi-vacuum-card'. It works perfectly when I added the first time the custom card, but after a few days, displays this message. 

From Incognito mode of Chrome the custom card is not displayed, anymore.

**Comment by benct** [comment]
Hmm.. I don't own any iOS devices, so I'm not sure how to figure out what is going wrong. It's working fine here in Chrome in incognito mode.. Have you updated the card to the latest version? Maybe you need to update Chrome?

When it fails in incognito Chrome, could you open Developer Tools and see if there are any error messages in the console window?

**Comment by CarpeDiemRo** [comment]
Everything works fine. Next day, the problem disappeared.

**Comment by benct** [comment]
Great!
