### ISSUE TITLE
Buttons are black on standard HA theme

### ISSUE THREAD

**Issue by kristomi** [benct/lovelace-xiaomi-vacuum-card#11]
Great card, I really appreciate the effort! I have the standard theme enabled in HASS (a quite fresh installation) and the buttons on the card are black, and thus hard to see. Is this a configurable option, or is something wrong?

**Comment by benct** [comment]
That is quite unfortunate.. I've just been testing this with a darker theme where the buttons are white by default.

I will try to add some support for custom styles when I get the time, but for now you have to either change your theme colors or use a card modding tool ([card-mod](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744) or [lovelace-card-modder](https://github.com/thomasloven/lovelace-card-modder)).

**Comment by kristomi** [comment]
That's fine, I'll manage!

**Comment by TheLastProject** [comment]
I'm sorry to report that change seems to have made things worse :(

![image](https://user-images.githubusercontent.com/1885159/61576280-5a878700-aad8-11e9-96dd-1898a0fe5a47.png)

Using [loveless-card-mod](https://github.com/thomasloven/lovelace-card-mod), adding the following style helped make it look decent (at least without background image):
```
style: |
  ha-card, ha-card * {
    color: var(--primary-text-color) !important;
    text-shadow: none !important;
  }
```

![image](https://user-images.githubusercontent.com/1885159/61576287-74c16500-aad8-11e9-94f6-069f9366bc0f.png)

It also looks good on dark themes with my style change:
![image](https://user-images.githubusercontent.com/1885159/61576297-b9e59700-aad8-11e9-87e9-503caf38f1c2.png)

**Comment by benct** [comment]
Hmm, everything seems to be working as expected when I use the latest changes in my setup..

Have you specified an `image` path in your card configuration? I did a quick test adding `image: /some/wrong/image/path.png` which gave me the same wrong colours as your example on the default theme. Try removing the `image` option or setting it to `false`?

**Comment by TheLastProject** [comment]
I didn't have image set, but setting it explicitly to false does fix it yes

**Comment by benct** [comment]
I just remembered the card defaults to the image path `/local/img/vacuum.png` if not specified, and adds the text colour and shadow if it thinks it has an image background. So setting `image: false` is necessary to get the correct text I guess.. which is a bit unfortunate. I might try to find a way to handle this better in the future :)
