### ISSUE TITLE
No card type configured.

### ISSUE THREAD

**Issue by stdestro** [benct/lovelace-xiaomi-vacuum-card#13]
HI. I get this error both in Firefox and in the ios app.

"No card type configured."

Running Hassio 0.96.0

My steps:
Installed custom card.
Added to lovelace: 
```
resources:
  - type: js
    url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
```
created card:

```
- type: custom:xiaomi-vacuum-card
  entity: vacuum.my_vacuum_cleaner
  image: /local/custom/folder/background.png
  name: Xiaomi Vacuum
  buttons: true
```

restarted Hassio
Cleared Firefox cache. restarted Firefox.
I always get the error

**Comment by benct** [comment]
Hmm.. Did you get this error before 0.96.0? I haven't upgraded yet, but not sure if it has anything to do with the new version of HA.

Using the developer tools in Firefox (press F12), are there any error messages in the console window?

**Comment by stdestro** [comment]
I installed the card for the first time after upgrading to 0.96, from Community store.
No error messages in Firefox console

**Comment by benct** [comment]
I see, I just added the card to the community store this week and have not tested it yet myself.

Are you sure you are using the correct paths in the configuration? Just had a look at the [HACS documentation](https://custom-components.github.io/hacs/faq/) which specifies that the files are downloaded to `<config_dir>/www/community/*`. Maybe you need the `/local/` prefix too. Other than that I'm not quite sure what could be wrong.

**Comment by stdestro** [comment]
I feel dumb. Sorry for wasting your time. It was totally my fault. 
I created a card using this syntax
```
- type: custom:xiaomi-vacuum-card
  entity: vacuum.my_vacuum_cleaner

```
but the right syntax is:

```
type: custom:xiaomi-vacuum-card
entity: vacuum.my_vacuum_cleaner
```
Sorry again.

Do you think it would be possible to add schedules like in this card?
( referring to this thread https://community.home-assistant.io/t/xiaomi-vacuum-cleaner-card/64456/5 )

<img width="383" alt="Annotation 2019-07-18 201337" src="https://user-images.githubusercontent.com/48654983/61481545-ca8ef380-a998-11e9-9e9f-9122d799a2e3.png">

**Comment by benct** [comment]
No problem, glad you figured it out :)

Unfortunately not. That card needs a lot of additional entities, templates and configuration in order to work properly with scheduling, which will be too difficult and complicated to integrate properly in this card.
