### ISSUE TITLE
Add cleaning area and time & other enhancements

### ISSUE THREAD

**Issue by dedors** [benct/lovelace-xiaomi-vacuum-card#14]
I'm migrating over from my custom lovelace card, which is basically the same, but I do miss stats from the last vacuum tour: cleaning_time and cleaned_area.

Also the state of vacuum.name is not the same as vacuum.name.status (docked vs charging). I used vacuum.name as title.

Any plans on adding that?

What also be a useful info: how long ago (in hours) was the last clean (from clean_stop: 2019-07-24T17:03:04).

And something for future plans, maybe when adding fan speeds, it might be an idea to also add "do not disturb" toggle&time?

**Comment by benct** [comment]
Sorry for the late reply, and thank you for the suggestions.

The docked vs. charging has previously bothered me and I have had plans to support this for a while. Several people have also requested to add more information like last clean etc., so I will probably add some of this as an optional feature in a future release.

I am currently not planning on adding more complex fields like fan speed selection or time toggling/scheduling. Fan speed can be set by clicking on the card, showing the more_info dialog.

**Comment by benct** [comment]
Setting fan speed (mode) and adding additional attributes is now supported in version `4.0.0`
