### ISSUE TITLE
Support for Valetudo/MQTT vacuum

### ISSUE THREAD

**Issue by rdehuyss** [benct/lovelace-xiaomi-vacuum-card#15]
First of all, thanks for this nice card!

I'm currently trying to integrate it but for some reason, all my attributes are named differently than what you use in your js file (see the attached screenshot): 

![valetudo_attributes](https://user-images.githubusercontent.com/567842/62395692-509e6300-b571-11e9-8cbc-b7a12a49a024.png)

Here, I have an attribute mainBrush instead of main_brush. Any idea why that would be?

I'm using Valetudo/dustcloud firmware on my RoboRock S50.

Cheers,
Ronald

**Comment by benct** [comment]
Hmm, very strange. I guess different vendors/firmware are implemented differently in HAs vacuum support. I should however be able to add support for the attribute differences you have provided. I'll try to add this as soon as I have the time.

**Comment by JackApple1337** [comment]
I've flashed a custom firmware to my Roborock S50 as well, to cut it off from the Xiaomi Cloud and had the same issue as @rdehuyss. The vendor change to `valetudo` works fine for me and now I'm seeing all those infos. I guess you could add it to the README.md and close the issue.

Thanks for you great work. =)

**Comment by rdehuyss** [comment]
Works like a charm!
