### ISSUE TITLE
Add Neato Support

### ISSUE THREAD

**Issue by faspina** [benct/lovelace-xiaomi-vacuum-card#16]
Would love for you to add neato support. What do you need from me to make that happen I have a Botvac D4

**Comment by benct** [comment]
Sure! I would need to know the attribute keys and services available on your vacuum entity. Give me a screenshot of the more_info dialog of your vacuum (like the one provided in #15) and paste the vacuum entity data fields found in the dev state page of your HA instance (<your-HA-url>/dev-state).

**Comment by Sleeepy2** [comment]
![image](https://user-images.githubusercontent.com/1533684/72385051-aebc9e00-36ec-11ea-93d6-5ae223e47c41.png)

Not sure why they didn't give you the more info but I will.
Also sort of separate issue setting the labels to false doesn't hide them

type: 'custom:xiaomi-vacuum-card'
entity: vacuum.neato
image: /local/custom/folder/background.png
name: My Vacuum
vendor: neato
labels:
  main_brush: false
  side_brush: false
  filter: false
  sensor: false

**Comment by hmagrini** [comment]
> and paste the vacuum entity data fields found in the dev state page of your HA instance

hope this helps :) 
```
battery_level: 99
battery_icon: 'mdi:battery-charging-100'
status: Docked
clean_start: '2020-01-23 12:35:37'
clean_stop: '2020-01-23 13:56:31'
clean_area: 76.8928
clean_suspension_count: 0
clean_suspension_time: 0
clean_pause_time: 81
clean_error_time: 0
battery_level_at_clean_start: 100
battery_level_at_clean_end: 45
launched_from: app
friendly_name: some-name
icon: 'mdi:robot-vacuum-variant'
supported_features: 15964
```

**Comment by baurmatt** [comment]
That would be awesome! :) I have a Neato D5 which I'd like to be integrated! If I can help in any way, please let me know! :)

**Comment by benct** [comment]
Supported in version `4.0.0` with `vendor: neato`. Let me know if something looks wrong, as it is difficult to test without the actual vacuum.
