### ISSUE TITLE
Info lost when vendor: ecovacs

### ISSUE THREAD

**Issue by woody4165** [benct/lovelace-xiaomi-vacuum-card#17]
Hi and thanks for sharing this card!

I have an Ecovacs Ozmo 900 and when I set ecovacs as vendor the info related to main_brush, side_brush, filter and sensor disappear.

If I don't set the vendor I just see the labels, but no info.

The info are visible in HA 

![Schermata 2019-08-28 alle 17 55 32](https://user-images.githubusercontent.com/6501444/63950874-172c1b00-ca7d-11e9-826d-c09e0e5f5dba.png)

and the attributes name are

```
component_main_brush: 29861
component_side_brush: 14855
component_filter: 11861
```

Do you think they can be shown in same way?

Thanks

**Comment by benct** [comment]
Seems like you have some different attribute fields, similarly as reported in #15. I will try to add support for yours too when I can.

Do you know of what unit those value are? Seconds? Minutes?

**Comment by woody4165** [comment]
Thanks @benct 

It seems a strange unit like it has to be divided by 100 to be transformed in hours.

component main brush 29820 = Spazzola principale 299 hours
component side brush 14811 = Spazzola laterale 149 hours
component filter 11820 = Filtro 119 hours

![Screenshot_2019-09-02-14-42-09-676_com android chrome](https://user-images.githubusercontent.com/6501444/64117265-00dfd100-cd95-11e9-9ba0-a4eb235361c7.png)

![Screenshot_2019-09-02-14-42-17-345_com eco global app](https://user-images.githubusercontent.com/6501444/64117269-00dfd100-cd95-11e9-8fe7-6eeb880a92d5.png)

**Comment by lbrichet** [comment]
Hello,

Just to say I have same model and same issue :)

**Comment by benct** [comment]
Sorry for taking so long. Please upgrade to the latest version and try setting the `vendor` to `ecovacs_ozmo`. As I do not have this vacuum/model, I hope you can do the testing for me. Hope it works!

**Comment by lbrichet** [comment]
Thank you very much !
FYI, I had the same request to display component_xxx but I don't have an osmo model.

I'll try anyway and give you feedback.

**Comment by lbrichet** [comment]
![image](https://user-images.githubusercontent.com/36230291/67016575-af976100-f0f8-11e9-9b89-09d377e70c79.png)

Small issue with Status and Power (power should be Max).
Also, perhaps you could round to integers.

Thank you again !

**Comment by woody4165** [comment]
Thanks @benct !

same small issues as @lbrichet

**Comment by benct** [comment]
Thanks for the quick response! Just pushed a fix for the `undefined` values and added rounding of the numbers.

The "power" uses the value of the `fan_speed` option. Is that not set to `normal`?

**Comment by woody4165** [comment]
My fan speed on the app is set to Max

![Schermata 2019-10-17 alle 16 19 32](https://user-images.githubusercontent.com/6501444/67017959-cccd2f00-f0fa-11e9-9862-b22f70689872.png)

**Comment by lbrichet** [comment]
Nevermind, it seems to be an issue with the integration.
It's set to Max on the Deebot but HA report Normal...

The Undefined is now gone ! Thanks !!

![image](https://user-images.githubusercontent.com/36230291/67018347-64328200-f0fb-11e9-8593-16efeedecc61.png)

**Comment by benct** [comment]
Is the official brand or model name of your vacuums Deebot? I might change the vendor from `ecovacs_ozmo` to `deebot` in that case.

**Comment by lbrichet** [comment]
Ecovacs is the brand, Deebot the name of their Vacuum and Ozm0 is a cleaning option :)
I have the Deebot 900 without the cleaning option so not Ozmo

https://www.ecovacs.com/fr/deebot-robotic-vacuum-cleaner

**Comment by woody4165** [comment]
Instead I have Deebot 900 Ozmo ;-)

**Comment by benct** [comment]
I see, thanks for clearing that up :) Changed vendor to `deebot` in version 2.3.1.

**Comment by woody4165** [comment]
so now no more `ecovacs` and `ecovacs_ozmo`, just `deebot` ?

**Comment by lbrichet** [comment]
Ok ! Perhaps one small last quick question :)
Do you know how/why have that card some shadowed font ? it's the only one in my GUI

**Comment by lbrichet** [comment]
Ok looks Great 👍 

Do you know what capteurs should be ?

![image](https://user-images.githubusercontent.com/36230291/67020365-63e7b600-f0fe-11e9-9395-2b27add63b76.png)

**Comment by woody4165** [comment]
Thanks!

It's working really fine with `vendor: deebot`

![Schermata 2019-10-17 alle 16 52 55](https://user-images.githubusercontent.com/6501444/67020500-98f40880-f0fe-11e9-93d2-2c78578f2f81.png)

**Comment by benct** [comment]
Sensor (capteurs?) is the time left until you should clean the sensors (supported by Xiaomi, but unfortunately not your vacuum). I haven't found a nice way to hide that row for ecovacs/deebot yet, but I'll try to figure something out later some time.
