### ISSUE TITLE
Background image not loading

### ISSUE THREAD

**Issue by welo78** [benct/lovelace-xiaomi-vacuum-card#18]
Hello I installed your card via HACS but I have been having problems with the background image not loading at all. I tried everything from /local/img to /config/img even copying the whole img folder everywhere but it still does not load. Any help ?

![image](https://user-images.githubusercontent.com/42773655/66510629-b0673c00-ead5-11e9-9b3e-1d5e9823662e.png)

**Comment by benct** [comment]
I've not tried using HACS so I'm not sure how it works regarding images. I'm guessing you have to manually add/copy/upload the [vacuum image](https://raw.githubusercontent.com/benct/lovelace-xiaomi-vacuum-card/master/img/vacuum.png) to your www/<image> folder.

If you have the image at <your-HA-folder>/www/img/vacuum.png, the configuration should be `image: /local/img/vacuum.png`.
