### ISSUE TITLE
HACS: Images are not installed

### ISSUE THREAD

**Issue by cdrfun** [benct/lovelace-xiaomi-vacuum-card#19]
When using HACS the images are not avaiable.

**Comment by pepeEL** [comment]
i use path on my Hassio on Hassos 
image: /local/img/vacuum.png

and image is not show. I compy manual image to this path and it is in this location.

**Comment by varzaman** [comment]
I'm also having this problem.

**Comment by tiagofreire-pt** [comment]
> i use path on my Hassio on Hassos
> image: /local/img/vacuum.png
> 
> and image is not show. I compy manual image to this path and it is in this location.

With HACS, use this image code line:

`image: /local/community/lovelace-xiaomi-vacuum-card/vacuum.jpg`

**Comment by etamtlosz** [comment]
it's png not jpg

> > i use path on my Hassio on Hassos
> > image: /local/img/vacuum.png
> > and image is not show. I compy manual image to this path and it is in this location.
> 
> With HACS, use this image code line:
> 
> `image: /local/community/lovelace-xiaomi-vacuum-card/vacuum.jpg`

it's png not jpg

**Comment by jacekpaszkowski** [comment]
Same problem here. No images

![image](https://user-images.githubusercontent.com/4264991/72335064-a8afc880-36be-11ea-8bfa-2df68e736a6f.png)

If i reload page there is no request fo the image file but when in design mode there are constant request (each ~2 sec) for file and the image is still not visible

![image](https://user-images.githubusercontent.com/4264991/72335255-f88e8f80-36be-11ea-84a5-2792572f184b.png)

**Comment by collse** [comment]
same behaviour as @jacekpaszkowski  - this is how I checked if its actually pulling the image but its not while my system is pulling others from the same path

**Comment by benct** [comment]
The HACS installation does not currently copy over the vacuum images, so I'm afraid you have to download the [default image](https://raw.githubusercontent.com/benct/lovelace-xiaomi-vacuum-card/master/img/vacuum.png) or another preferred image yourselfs until I get this fixed.

**Comment by cdrfun** [comment]
A good location for @benct's suggestion would be the `www/community` folder. this way the file can be referenced with `/community_plugin/vacuum.png` and HACS won't touch it.

For solving the issue it may be a solution to create a zip release and define it in the `hacs.json`? (https://hacs.xyz/docs/publish/start#hacsjson)
Another idea would be file an upstream feature request to HACS, so you can define additional files which shall also be downloaded.

**Comment by Mace404** [comment]
No matter what path or location I use, there is no request to open the image (checking using browser console).

**Comment by cdrfun** [comment]
@Mace404 Could you post your card-config?

**Comment by Mace404** [comment]
```
        - type: 'custom:xiaomi-vacuum-card'
          entity: vacuum.wong
          image: /local/img/vacuum.png
          vendor: valetudo
          buttons: false
```

**Comment by Neejoh** [comment]
Same here. I've tried adding the image to many locations, but all with the same result.
When I inspect the card in the developer tools, the inline background image style is wrong;
```html
<ha-card class="background" style="background-image: url('/local/custom/folder/background.png')">
```

Weird, this is not a path that is anywhere in the code of the plugin. But again, changing the `image:` config does not change the path to this image in the inline style.

**Comment by Neejoh** [comment]
I ended up just copying `vacuum.png` over to `/config/www/custom/folder/background.png` to get the background image to work.
Don't know why the yaml is ignored for this. It's not a fix of the bug of course, but at least I don't have a broken dashboard in HA.

**Comment by benct** [comment]
HACS doesn't seem to want to include additional files like images, so I'm closing this. Also, in version `4.0.0` background images have been disabled by default. If you specify an image path you will have to upload that image to the correct location too.
