### ISSUE TITLE
Compatibility with custom_updater

### ISSUE THREAD

**Issue by kugan49** [benct/lovelace-xiaomi-vacuum-card#2]
Can you integrate json infos for be able to use this system :
https://github.com/custom-components/custom_updater/wiki/components

**Comment by benct** [comment]
Will add support for this as soon as I have the time. Thanks for the suggestion.

**Comment by benct** [comment]
Just added some json info. I'm not using the custom updater component myself, so let me know if I'm missing anything.

**Comment by kugan49** [comment]
Very nice thank you everything is working.
thanks a lot again
