### ISSUE TITLE
Add option for "Labels" 

### ISSUE THREAD

**Issue by niccolobusato** [benct/lovelace-xiaomi-vacuum-card#20]
add true/false option for labels

**Comment by niccolobusato** [comment]
something like this: 
<img width="287" alt="vacuum" src="https://user-images.githubusercontent.com/44100360/68315624-56e43400-00b8-11ea-8c84-72f4892b3557.png">

**Comment by benct** [comment]
Almost nothing left of the card! 😜
But sure, should be easy enough to implement, when I get the time.

**Comment by niccolobusato** [comment]
I Know.. but i can use this with my "dumb" mqtt vacuum (controlled via node red and broadlink ir)

**Comment by benct** [comment]
Sorry for the late support. Setting `labels: false` in the configuration should now remove the labels part.
