### ISSUE TITLE
RoboRock S6 Fan mode not "translated"

### ISSUE THREAD

**Issue by freemann** [benct/lovelace-xiaomi-vacuum-card#21]
The card is not  "translating" the fan mode code of the S6 to readable/understandable text, see screenshot;
![Screenshot - 08_11_2019 , 10_44_35](https://user-images.githubusercontent.com/601053/68466574-f4ed1100-0214-11ea-9b9d-e725bb61a6f1.png)

Codes are:
101: "Quiet"
102: "Balanced"
103: "Turbo"
104: "Max"

**Comment by tribut** [comment]
This appears to be a duplicate of https://github.com/rytilahti/python-miio/pull/468 (see also https://github.com/home-assistant/home-assistant/issues/17695 and https://github.com/rytilahti/python-miio/pull/523).

**Comment by benct** [comment]
As this seems to be a (soon-to-be-fixed?) bug in the xiaomi/miio integration itself, I will not be handling this in the lovelace card.

**Comment by hanseandersson** [comment]
So this is closed but it's still a problem..?
How can I change so it changes in percent instead?

**Comment by benct** [comment]
As mentioned in my last comment, this is not a bug in this card but a bug in the miio (Xiaomi) vacuum **integration** itself. See the links that @tribut posted in his comment further up, and comment on those issues instead :)
