### ISSUE TITLE
Add Eufy Robovac Support

### ISSUE THREAD

**Issue by silviudc** [benct/lovelace-xiaomi-vacuum-card#23]
I have an Eufy Robovac 15C Max and it would be great to add that to the list of supported models as this card looks very nice :)

**Comment by 3ative** [comment]
Agreed, I just got a ***Eufy RoboVac 30C*** set up in **HA** So would be nice to have status card for it.
Thnx

**Comment by benct** [comment]
I would need to know what attributes and services that vacuum integration provides. Could you post the data shown for you vacuum entity under HA's dev-states (`/developer-tools/state`) and possibly a screenshot of the more-info dialog (as in #17)? Thanks.

**Comment by 3ative** [comment]
@benct 
Sure thing...

**States:**
![vac1](https://user-images.githubusercontent.com/51385971/70909406-5919a680-2005-11ea-9f3a-5e6022b9f82f.JPG)


_In front end I just use a standard **Entity Card**_
![vac3](https://user-images.githubusercontent.com/51385971/70909518-8ebe8f80-2005-11ea-816f-687c43d9f334.JPG)


_And the **More Info** displays this:_
![vac2](https://user-images.githubusercontent.com/51385971/70909545-9ed66f00-2005-11ea-8f09-eb9043182ede.JPG)

**Comment by benct** [comment]
Could you fetch the latest updates and try to set `vendor: robovac`? Not sure I have all the correct service names, so please test the buttons :)

**Comment by 3ative** [comment]
Hmmm...
Card notworking, getting this:
![image](https://user-images.githubusercontent.com/51385971/70935271-bb8b9a80-2037-11ea-9676-4febe51cb2fc.png)

**Comment by silviudc** [comment]
> Could you fetch the latest updates and try to set `vendor: robovac`? Not sure I have all the correct service names, so please test the buttons :)

Yes it does, thanks

![image](https://user-images.githubusercontent.com/17740184/71261337-04dc3280-2335-11ea-9bec-d2d1d9b29529.png)

I am having an issue with the status however that is the integration's fault not the card's :)

**Comment by 3ative** [comment]
I still can't get the custom card to load. 😒
 - Installed via HACS, added the line to yaml file... nothing :(

```
resources:
  - type: js
    url: /local/xiaomi-vacuum-card.js
```

**Comment by silviudc** [comment]
```
- type: module
    url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
```

Try that, I think your -type is wrong

**Comment by 3ative** [comment]
Ok got it now, It was the spacing !!!
All working now with:
```
type: 'custom:xiaomi-vacuum-card'
buttons:
  spot: true
entity: vacuum.robovac
image: /local/img/vacuum.png
vendor: robovac
```
![image](https://user-images.githubusercontent.com/51385971/71267614-f6951300-2342-11ea-9883-340dea2fe24d.png)

And YES, I did stick 'Googly' Eyes on my RoboVac 🤣

Many thanks for making this 👌

**Comment by 3ative** [comment]
> ```
> - type: module
>   url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
> ```
> 
> Try that, I think your -type is wrong

Yes, I had previously tried that... However, I've just changed it back to
```
- type: js
```
And it still works - Seems either if fine. :)
