### ISSUE TITLE
Cannot read property 'setConfig' of undefined

### ISSUE THREAD

**Issue by Dinth** [benct/lovelace-xiaomi-vacuum-card#25]
I have installed latest Xiaomi Vacuum Card using HACS, but whenever i try to add the card (using GUI editor), im getting "Cannot read property 'setConfig' of undefined". Im trying to add modifed (with correct values) example from the documentation.

**Comment by Remlas** [comment]
Had the same problem ;)

Duplicate of #13 

So, in card config paste:
`type: 'custom:xiaomi-vacuum-card'
buttons: true
entity: vacuum.xiaomi_vacuum_cleaner
labels:
	battery: Bateria
	filter: Filtr
	main_brush: Główna Szczotka
	mode: Tryb
	sensor: Czujnik
	side_brush: Dodatkowa Szczotka
	status: Stan
`

**Comment by Dinth** [comment]
Lol, stupid me. 
Dzieki.
