### ISSUE TITLE
Allow customizing button action

### ISSUE THREAD

**Issue by jacekpaszkowski** [benct/lovelace-xiaomi-vacuum-card#26]
It would be nice to be able to customize actions when buttons are pressed. Eq. run custom script :)

**Comment by condemil** [comment]
I also wanted to propose to add custom button where you can define the icon and service to call.

**Comment by EelcoAV** [comment]
My Roomba only responds to  
      action: call-service
      service: vacuum.turn_on
Instead of the more usual "start" command
So I to would love to be able to customize the commands

**Comment by benct** [comment]
Supported in version `4.0.0`
