### ISSUE TITLE
Add the ability to hide labels individually

### ISSUE THREAD

**Issue by chansearrington** [benct/lovelace-xiaomi-vacuum-card#27]
I would love the ability to show/hide each label individually. I have this working well for my Roomba, but my Roomba doesn't have all of this information, nor do I want all this information displayed. But I do want some of it.

**Comment by benct** [comment]
Added support for roomba in the lastest version, try adding `vendor: roomba`.

If you want to hide attributes (labels), you can use the `attributes` object to set them to `false`:
```
attributes:
  main_brush: false
  side_brush: false
```

**Comment by chansearrington** [comment]
@benct awesome!!! Thanks!

**Comment by blizarazu** [comment]
This doesn't work with status, battery and mode. Do you plan to add this functionality also for these attributes? Thank you!
