### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by condemil** [benct/lovelace-xiaomi-vacuum-card#29]
The card adds the following error in console when reloading the page:

```
dumper.js:756 Uncaught (in promise) 
name: "YAMLException"
reason: "unacceptable kind of an object to dump [object Undefined]"
mark: undefined
message: "unacceptable kind of an object to dump [object Undefined]"
```

When I remove the card from page the error disappears.

**Comment by benct** [comment]
Haven't seen that kind of message before.. How are you adding the card? And what does you card configuration look like?

**Comment by condemil** [comment]
I have js file manually copied under `www/xiaomi-vacuum-card.js` and the following configuration:

```
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.vacuum
        name: false
        vendor: valetudo
        image: false
```

**Comment by benct** [comment]
Strange.. I have no idea what could cause this. Will have to do some further testing whenever I get the time.

**Comment by benct** [comment]
I cannot seem to reproduce this, so if it doesn't cause any problems except the console messages I'm not going to do anything about it for now.
