### ISSUE TITLE
Roborock S6 "mode" shows numbers

### ISSUE THREAD

**Issue by plissje** [benct/lovelace-xiaomi-vacuum-card#30]
Hey,
It seems that when trying to change the fan speed, aka mode, for Roborock S6 I get the same 102 mode number for everything but Gentle:
![image](https://user-images.githubusercontent.com/35014400/73444573-7f9b6300-4361-11ea-9fdb-b20cc61d6e43.png)

Is S6 even supported and if it is, may I know how can this be fixed?

**Comment by plissje** [comment]
It appears that this was already posted in its not an issue in the card.
Sorry :)

**Comment by benct** [comment]
No problem :) Linking issue to #21
