### ISSUE TITLE
"Mode" shows 102

### ISSUE THREAD

**Issue by jazbraz** [benct/lovelace-xiaomi-vacuum-card#33]
I have updated my xiaomi S5 with new firmware and notice that Mode shows a number instead of Silence, Standard or Turbo. Not a big deal/issue but to let you know and hopefully change it. Thanks for the work with the vaccum-card!!

**Comment by benct** [comment]
I recently did the same and also get the number value for modes now. However, this is most likely the same problem as #21. The translation of the modes are handled by the vacuum integration in HA and not by this card.

HA core issue here: https://github.com/home-assistant/core/issues/31268
