### ISSUE TITLE
Allow custimizing sensor entity

### ISSUE THREAD

**Issue by jacekpaszkowski** [benct/lovelace-xiaomi-vacuum-card#35]
It would be grate to be able to change source entity of statate value.
eg. i would like to change "mode" entity

Now the value if from "fan_speed" attribute and it displays numeric value
![image](https://user-images.githubusercontent.com/4264991/77182893-c722ad80-6acd-11ea-89a9-04c1da6f4804.png)

i have template sensor which translates numeric values to user friendly names

**Comment by benct** [comment]
The fan speed entity name should hopefully be fixed soon by the vacuum integration people, so I will unfortunately not be adding support for custom entities/states like this as it would just add a lot of unnecessary complexity.
