### ISSUE TITLE
Roomba Start Button

### ISSUE THREAD

**Issue by Veldkornet** [benct/lovelace-xiaomi-vacuum-card#36]
When configured with an iRobot Roomba, the start button does nothing.

All the other buttons seem to work as expected though.

**Comment by benct** [comment]
Does it work if you set `vendor: ecovacs`? This uses another service name to start the vacuum, so just need to test if that is the case.

**Comment by Veldkornet** [comment]
Yes it does

**Comment by Veldkornet** [comment]
Seems to be fixed somehow with HA 0.109 and later
