### ISSUE TITLE
Path to background

### ISSUE THREAD

**Issue by kugan49** [benct/lovelace-xiaomi-vacuum-card#4]
Can you modify your js file to make path to background standard :
/local/ should be in background path of yaml not in your js.
and name it "image" instead of "background".

See official example : 
https://www.home-assistant.io/lovelace/picture-glance/
https://www.home-assistant.io/lovelace/picture-elements/

Thank you

**Comment by benct** [comment]
Good suggestions, will change these in the next version. Thanks!
