### ISSUE TITLE
Custom card won't load

### ISSUE THREAD

**Issue by kiwijunglist** [benct/lovelace-xiaomi-vacuum-card#45]
I had trouble getting this to work initially and spent almost an hour on it.

Can you update the installation instruction for HACS.

**Step One (Install)**

Open HACS, click plugins, then find the plugin called "(Xiaomi) Vacuum Card" and click install

**Step Two (Add lovelace resources)**

After the plugin has finished installing click the "add to lovelace" button

<img width="415" alt="vac06" src="https://user-images.githubusercontent.com/1858199/80560852-96bc2080-8a36-11ea-8301-3ac408456f0b.png">

**Step Three (Add the custom card)**

```
type: custom:xiaomi-vacuum-card
  entity: vacuum.vacuum_name
```
<img width="757" alt="vac07" src="https://user-images.githubusercontent.com/1858199/80560999-07633d00-8a37-11ea-8f9c-e2445036631f.png">

**Comment by kiwijunglist** [comment]
<img width="655" alt="vac03" src="https://user-images.githubusercontent.com/1858199/80557134-04ae1b00-8a2a-11ea-9d0f-17c05decc73a.png">

<img width="1308" alt="vac04" src="https://user-images.githubusercontent.com/1858199/80557138-0841a200-8a2a-11ea-9aca-7ae57ff6f853.png">

**Comment by kiwijunglist** [comment]
The problems I encountered are because the instructions are not up to date / wrong

**Problem 1**

```- type: custom:xiaomi-vacuum-card
  entity: vacuum.xiaomi_vacuum_cleaner
```

Should be

```
type: custom:xiaomi-vacuum-card
  entity: vacuum.xiaomi_vacuum_cleaner
```

**Problem 2**

OR install using HACS and add this instead:

```resources:
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: module
```

This should be

```
/hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
```
or
```
/hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
local/community/lovelace-xiaomi-vacuum-card
```

**Comment by Silandor** [comment]
How do you get the HACS to look like that? :O Is there something wrong with my HACS? I just installed it and for me the HACS menu dont look anything like youre on the pics, with like "Settings" "Plugins" Themes" and "Installed"

I came here because i couldent get my Xiaomi vacuum card to work at all. Adding some pics so you can see how mine looks

![1](https://user-images.githubusercontent.com/65692323/82701661-e32f0080-9c70-11ea-8152-322d1d13b740.JPG)
![2](https://user-images.githubusercontent.com/65692323/82701667-e629f100-9c70-11ea-92cb-44a408e1f5a6.JPG)

**Comment by kiwijunglist** [comment]
mine:
<img width="1193" alt="screen01" src="https://user-images.githubusercontent.com/1858199/82717843-ebc81b00-9cf2-11ea-9fe8-3a4d246daa10.png">

**Comment by Silandor** [comment]
Ye that looks way better then at my Setup. Like more control over the plugins and themes etc. Is it an older version of HAC?

**Comment by kiwijunglist** [comment]
Latest
