### ISSUE TITLE
Roomba Status Unavailable in HA 0.109

### ISSUE THREAD

**Issue by Veldkornet** [benct/lovelace-xiaomi-vacuum-card#46]
Vacuum Card: v3.0.1
HomeAssistant 0.109

After updating to HA 0.109, the Roomba configuration was updated. The Roomba itself still works fine, but the status on the card shows “Unavailable”

![image](https://user-images.githubusercontent.com/10297361/80638305-8751cd00-8a60-11ea-9408-43cb5f56b8c1.jpeg)

**Comment by tibortiz** [comment]
Maybe it's due to the new integration of Roomba vaccum with release v0.109

**Comment by tibortiz** [comment]
@Veldkornet Issue fixed with HA 0.109.2

**Comment by Veldkornet** [comment]
Confirmed, it’s fixed in the latest HA
