### ISSUE TITLE
link to changelog

### ISSUE THREAD

**Issue by kugan49** [benct/lovelace-xiaomi-vacuum-card#5]
Hi,
Thank you for your work.
I saw in your tracker.json that link to changelog is wrong.
it is [https://github.com/benct/lovelace-xiaomi-vacuum-card/blob/master/CHANGELOG.md](https://github.com/benct/lovelace-xiaomi-vacuum-card/blob/master/CHANGELOG.md)

Now I Will fork your work to allow traducing text, I hope you agree

**Comment by benct** [comment]
You are correct, thanks for pointing that out :)

**Comment by benct** [comment]
Fixed in 88236e87f846f4bddde8beea2e0262bae4136759.
