### ISSUE TITLE
Feature Request / I might build it myself

### ISSUE THREAD

**Issue by simonwood0609** [benct/lovelace-xiaomi-vacuum-card#51]
Thanks so much for making & maintaining this card.

I'm wanting to add a second row of buttons to trigger zoned cleanups and issue a goto bin command.

Have you seen any active examples of this / are you willing to attempt it?

Otherwise I'll make a fork and try to build it myself.

**Comment by benct** [comment]
Yes, I would like to add the possibility to add custom buttons. Follow up in #26.
