### ISSUE TITLE
Not loaded in Lovelace, I'm new

### ISSUE THREAD

**Issue by Judocrafter** [benct/lovelace-xiaomi-vacuum-card#52]
Hi Guys

I'm new here.

I installed lovelace-xiaomi-vacuum-card via Hacs.

now I have the following error message:
Not loaded in Lovelace, You gave 1 Lovelace elements that are not loaded properly in Lovelace

How can I fix this or how can I add this card?

![image](https://user-images.githubusercontent.com/42749857/88798530-512e0180-d1a5-11ea-8e78-ccb60467581c.png)

![image](https://user-images.githubusercontent.com/42749857/88798538-53905b80-d1a5-11ea-827c-ce18a7aff654.png)

**Comment by benct** [comment]
After the plugin has finished installing click the "add to lovelace" button. See guide in #45.
