### ISSUE TITLE
Background image in v4

### ISSUE THREAD

**Issue by jscherry** [benct/lovelace-xiaomi-vacuum-card#54]
Just updated to version 4 and the background image quit working. Reverted back to previous version and background image came back?

**Comment by andysaab** [comment]
Hello!
Just place "image: /local/img/vacuum.png" to card config.

**Comment by benct** [comment]
> Changed: Make background image disabled by default

In version 4 it is not enabled by default, you have to define an image path and filename.
Add `image: /local/img/vacuum.png` (or similar) to your configuration.
