### ISSUE TITLE
Fan_speed: 60

### ISSUE THREAD

**Issue by fjterrada69** [benct/lovelace-xiaomi-vacuum-card#55]
![Screenshot_2020-09-24-00-20-46-716_io homeassistant companion android](https://user-images.githubusercontent.com/35507949/94075628-d6c3db80-fdfb-11ea-95c1-5e6ebf82f613.jpg)
No me aparece en fan_speed el modo de limpieza de la xiaomi vaccum solo me aparece el valor de 60.
Aunque cambie el modo de limpieza siempre me sigue apareciendo 60.

**Comment by benct** [comment]
(sorry about the google translate, I cannot speak Spanish..)

Esta tarjeta no tiene control sobre los valores fan_speed. Aquellos provienen directamente de las integraciones de vacío en HA y la tarjeta simplemente los muestra. Así que, lamentablemente, no puedo cambiar ni corregir esos valores.

¿Podría copiar los valores que se muestran en la entidad de vacío en las herramientas de desarrollo de HA (`/developer-tools/state`), para que pueda ver qué está pasando?

**Comment by fjterrada69** [comment]
![Screenshot_2020-09-24-06-53-12-391_io homeassistant companion android](https://user-images.githubusercontent.com/35507949/94102546-a77c9100-fe32-11ea-8a0c-40239ddc0e01.jpg)
No te preocupes por la traducción, te entiendo bastante bien. 
Añado los valores de la herramienta de desarrollo, ahí también me aparece a 60 el valor. 
Muchas gracias.

**Comment by benct** [comment]
Los valores en fan_speed_list son correctos, por lo que es extraño que fan_speed no lo sea. Tendrá que crear un problema con la integración de HA en sí, de ahí provienen estos valores.

https://github.com/home-assistant/core/tree/dev/homeassistant/components/xiaomi_miio

**Comment by fjterrada69** [comment]
Entonces porque al hacer clic con el ratón en el valor 60 de fan_speed de
la tarjeta me sale una lista desplegable con las opciones Silent, Standard,
Medium, Turbo y Gentle?
