### ISSUE TITLE
Non show vacuum card after update HA to v.0116b0

### ISSUE THREAD

**Issue by andysaab** [benct/lovelace-xiaomi-vacuum-card#56]
Hello!
After update to beta version of HA the vacuum card non show on web-UI.
No problem with vacuum, no problem with card code editor - just no image on web-page.
![image](https://user-images.githubusercontent.com/56047524/94839945-5b2be500-0420-11eb-9ee3-ff138cff9a36.png)
![image](https://user-images.githubusercontent.com/56047524/94840094-93cbbe80-0420-11eb-8067-190938500390.png)

Could you fix it?

**Comment by benct** [comment]
They are adding a breaking change in 0.116, ref. [this article](https://developers.home-assistant.io/blog/2020/09/30/customViewChanges). I'll try to fix this before or when they release the new version.
