### ISSUE TITLE
No sensor for emptying the bin on roborock s5?

### ISSUE THREAD

**Issue by gurkburk76** [benct/lovelace-xiaomi-vacuum-card#58]
So i have the roborock s5 (reports as having supported_features: 14204) that works very well, there is just one thing missing.
When i use the xiaomi app i get reports when it's time to empty the bin but i can't figure out if it's possible to detect that via this card and handle the warning via home assistant.
Is this a feature not included in the API you use to get info from the device?

**Comment by benct** [comment]
I have the same `supported_features` and cannot find any data on the bin. So the HA [integration](https://github.com/home-assistant/core/tree/dev/homeassistant/components/xiaomi_miio) does not seem to include this. You could raise an issue with them and see if they can add it.
