### ISSUE TITLE
Lovelace card no longer displays in 0.116

### ISSUE THREAD

**Issue by talondnb** [benct/lovelace-xiaomi-vacuum-card#59]
As per title, since updating to 0.116 the card no longer displays.

**Comment by benct** [comment]
This should have been fixed in `v4.0.1`, ref #56. Have you upgraded the card?

**Comment by talondnb** [comment]
Yes, I'm already on 4.0.1.

edit: sorry I've just done a hard reload in chrome and it appeared!
