### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by K-RAD** [benct/lovelace-xiaomi-vacuum-card#63]
Installed via HACS and added resource in Config / Lovelace dashboards / Resources
`/hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js`
and I still can't see/add the card

```
No card type configured.
- type: 'custom:xiaomi-vacuum-card'
```

**Comment by pafnow** [comment]
How did u fix this issue ?
