### ISSUE TITLE
feature request : second row for new buttons

### ISSUE THREAD

**Issue by NicoLeOca** [benct/lovelace-xiaomi-vacuum-card#64]
Hi,
Thanks for this card, I like the design and it's efficiency.
I add my own buttons (one per room)
Would it be possible to seperate them onto a second row please?
To improve the visibility as you can see below

<img width="487" alt="Capture d’écran 2020-12-20 à 21 24 43" src="https://user-images.githubusercontent.com/9487685/102723678-d9a26f80-4309-11eb-9238-77ab1ddc4fff.png">

**Comment by benct** [comment]
Would recommend trying [card-mod](https://github.com/thomasloven/lovelace-card-mod) and add some CSS to split the buttons into rows. It's not that easy to add specific support for this when people use a varying number of buttons..
