### ISSUE TITLE
No Card Type Found

### ISSUE THREAD

**Issue by NOTORIOUSVR** [benct/lovelace-xiaomi-vacuum-card#66]
Installed manually or with HACS I cannot get the card to show up

Home Assistant 2020.12.2

Lovelace card shows this in red:
No card type configured
- type: 'custom:xiaomi-vacuum-card'
  entity: vacuum.xiaomi_vacuum_cleaner

**Comment by asgeirogm** [comment]
Same issue here, on Home Assistant 2020.12.1, installed with HACS.

**Comment by NOTORIOUSVR** [comment]
Issue was the syntax on the main page for LL is incorrect.

instructions show:
`- type: custom:xiaomi-vacuum-card
  entity: vacuum.xiaomi_vacuum_cleaner`

should be:
`type: custom:xiaomi-vacuum-card
 entity: vacuum.xiaomi_vacuum_cleaner`
