### ISSUE TITLE
Ecovacs Button

### ISSUE THREAD

**Issue by eps000** [benct/lovelace-xiaomi-vacuum-card#7]
Thanks for the great card!
All the buttons work as they should except for the stop button on my ecovacs, which just acts as the return to home button. Would it be possible to replace the stop button with the spot clean option? The service call is "vacuum.clean_spot" for ecovacs.

**Comment by benct** [comment]
Thank you for the feedback and suggestion.

I could probably do that. I don't have an Ecovacs vacuum myself, nor have I used spot cleaning, so I'm not sure how much I will get to test the implementation when I get to it. Do you know if the clean_spot service call requires any other options, like which "spot" to clean or something? If there are no required options other than entity_id, I'll try to add this soon.

**Comment by eps000** [comment]
There are no other requirements it’s just the service call and entity id. I would gladly test it out on my ecovacs.  Thanks!

**Comment by benct** [comment]
Added options to show/hide individual buttons so that everyone can customize their buttons. I also set the ecovacs defaults to show clean spot instead of stop. Let me know if anything is not working as intended :)
