### ISSUE TITLE
Background image stopped working

### ISSUE THREAD

**Issue by jscherry** [benct/lovelace-xiaomi-vacuum-card#70]
I've been using this card for almost a year and the background image has always worked properly. Today I noticed it is no longer working? My card config is:
image: /local/www/img/vacuum.png
entity: vacuum.xiaomi_vacuum_cleaner
name: Roborock Vacuum
type: 'custom:xiaomi-vacuum-card'

**Comment by jscherry** [comment]
I just created a new card with this config and still no background?
type: 'custom:xiaomi-vacuum-card'
entity: vacuum.xiaomi_vacuum_cleaner
image: /local/www/img/vacuum.png
name: Roborock Vacuum
vendor: xiaomi

**Comment by 7R0J4Ner** [comment]
Didnt work for me either.

I went into File Editor, locatet the Picture in /config/www/community/lovelace-xiaomi-vacuum-card/vacuum.png
and copied the whole path (for me http://homeassistant.local:8123/api/hassio_ingress/.../api/file?filename=/config/www/community/lovelace-xiaomi-vacuum-card/vacuum.png)

Using this Path worked for me

**Comment by benct** [comment]
No reason why this should suddenly not work, if not the image file has been moved or removed.. check that it exists in `<config dir>/www/img` or move it to the plugin directory and update the path in the card config, as suggested above.
