### ISSUE TITLE
No image

### ISSUE THREAD

**Issue by jscherry** [benct/lovelace-xiaomi-vacuum-card#76]
Is it still possible to show the image in the background? I had this working for quite some time then the image quit working months ago.

**Comment by dckiller51** [comment]
Hi,

No problem with image.

Exemple

```
image: /local/images/vacuum.png
```

**Comment by tomaszduda23** [comment]
The image stopped working after update of home assistant. I changed path to the image and it works again.

```      
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.roborock_vacuum_s5
        image: /local/custom_lovelace/xiaomi_vacuum_card/img/vacuum.png
```

The image is at `config/www/custom_lovelace/xiaomi_vacuum_card/img/vacuum.png`

**Comment by Skylinar** [comment]
for me it was 
`image: /local/community/lovelace-xiaomi-vacuum-card/vacuum.png`

**Comment by shadsnz** [comment]
Thanks Skylinar! That fixed the same issue for me.
