### ISSUE TITLE
request for input_select: for areas

### ISSUE THREAD

**Issue by vMeph** [benct/lovelace-xiaomi-vacuum-card#8]
would be nice to option for select areas to clean up

**Comment by benct** [comment]
Hi. This has been suggested earlier on the HA forums and I have plans to add it in the future. It requires quite a bit of work, so I cannot say when I will be able to do this yet. Any contribution would be welcome.

**Comment by kugan49** [comment]
https://github.com/kugan49/HA_Config/blob/master/capture/20_Vacuum.png
I have this but there is a lot of scripts for this (see zone section for more) : 
https://github.com/kugan49/HA_Config/blob/master/config/packages/xiaomi_vacuum.yaml

**Comment by benct** [comment]
This adds too much complexity to the card so I've decided not to implement this. I might add support for custom button(s) that can call a service (ie. area cleaning), but we'll see what I have time to do.
