### ISSUE TITLE
No mopping

### ISSUE THREAD

**Issue by wsslfnstr** [benct/lovelace-xiaomi-vacuum-card#81]
I want to be able to disable mopping when i click start. 
Currently i can set the vacuuming power but not the mopping power/vibrating power so it will always mop.

I am using a roborock s7

**Comment by benct** [comment]
What attributes does the S7 vacuum entity have? Can be found under /developer-tools/state

**Comment by wsslfnstr** [comment]
Those are all the attributes:
![Screenshot_20211107-111127](https://user-images.githubusercontent.com/16176769/140640804-3a479d83-e0d9-4cdb-9eba-8c241546c011.jpg)
So I see now that there is no moping power attribute. So they need to add it before you can implement :(

**Comment by benct** [comment]
Yep.. let me know when/if they add them!

**Comment by Skylinar** [comment]
would love to have that feature as well, but i assume there is no update on this one?
