### ISSUE TITLE
Ecovacs Ozmo 920 No Stats

### ISSUE THREAD

**Issue by rossbate** [benct/lovelace-xiaomi-vacuum-card#85]
I have an Ecovacs Ozmo 920 and state and brush/filter stats don't show up using vendor ecovacs or deebot.
The state shows up if i use valetudo as the vendor, but nothing else.
The brush/filter is not an attribute but a sensor as such: 
(Main Brush) sensor.<vac name>_brush 
(Side Brush) sensor.<vac name>_sidebrush
(filter) sensor.<vac name>_heap

I have tried to update the xiaomi-vacuum-card.js with no luck (as i don't know what im doing :) )

**Comment by zeridon** [comment]
duplicate of #84
