### ISSUE TITLE
No parts information

### ISSUE THREAD

**Issue by krzysiek2788** [benct/lovelace-xiaomi-vacuum-card#88]
Hi,
After today update 4.4.0 I have 0% life time where in fact I have 100% yesterday it was working fine:
![image](https://user-images.githubusercontent.com/61471407/140647955-6d069693-a85c-4617-b694-a6dabc120ac1.png)
Viomi S9 data
![image](https://user-images.githubusercontent.com/61471407/140647972-fae322be-e90b-4fb7-981e-3873b99fc25e.png)
card configuration
![image](https://user-images.githubusercontent.com/61471407/140647998-5284bad6-384e-4037-9eab-3d5e8d7a02c6.png)

**Comment by benct** [comment]
If your vacuum still has data as attributes and not separate sensors, you'll probably need to stay on version `4.3.0` for now. I'll see what I can do to support both..
