### ISSUE TITLE
Add button fan speed

### ISSUE THREAD

**Issue by trantuan4889** [benct/lovelace-xiaomi-vacuum-card#9]
Pls add button change fan speed for Ecovacs Vaccum
service: vacuum.set_fan_speed
{
  "entity_id": "vacuum.e000p8u545678513465",
  "fan_speed":"high" or "fan_speed":"nomal" 
}

**Comment by benct** [comment]
I think this will have to be an input_select, similarly to the zoned area suggestion in issue #8.

For now you should be able to change the fan speed by clicking the card itself, bringing up the default 'more-info' dialog for the vacuum and selecting the speed there.

**Comment by cotwild** [comment]
Thanks for your great work! I love this card.

I use a XIAOMI S5 with valetudo 0.40 where there are some additional "Fan Speeds" or better modes:
Actualy i can choose in your card: "Quiet, Balanced, Turbo, Max"
But i got the additional modes: "Whisper, Mop"

Is there a way I can add those modes?

**Comment by benct** [comment]
If I am able to add support for a custom fan speed control in some way in the future, I will definitely try to add those modes too (for valetudo) :)

**Comment by benct** [comment]
I want to keep the card fairly simple and clean, and as it is possible (and very simple) to select fan speeds in the more-info dialog, I've decided to not implement this.
