### ISSUE TITLE
Custom Attributes

### ISSUE THREAD

**Issue by Shermer321** [benct/lovelace-xiaomi-vacuum-card#90]
I know this isn't the right spot, but it is in regards to your card. How do I fine what attributes and keys to use? I tried adding some custom ones and none of them work. Any help would be great!

Xiami Mii app, using Roborock S7

**Comment by Shermer321** [comment]
Is anyone able to tell me how to add a custom attribute? I know my entity name but I cannot get it to show on the card. For example, what is the key?

**Comment by benct** [comment]
Go to `<your-ha-url>/developer-tools/state` and search for the vacuum entity. It should show you what attributes it has.
