### ISSUE TITLE
v4.4.0 Missing button..

### ISSUE THREAD

**Issue by shadowdavis** [benct/lovelace-xiaomi-vacuum-card#91]
It can be used normally before, but the buttons that I suddenly found today are gone. And in fact, they can be clicked. I don’t know if it’s an updated problem. Now it’s down to version 4.2 .0 and the button appears again. The following is my configuration:

>   - type: custom:xiaomi-vacuum-card
    entity: vacuum.roborock_s5
    name: false
    attributes:
      sensor: false
    buttons:
      locate: false

**Comment by Tamsy** [comment]
Assuming your HA instance was just updated to HA >= 2021.11.0 ?

A solution to your problem can be found here: https://github.com/benct/lovelace-xiaomi-vacuum-card/issues/84

Hint: "entity: vacuum.roborock_s5" might have to be corrected.

You could have found this by yourself by just investing a little more time and browsing trough the issue tracker for the open and closed issues ...

**Comment by Bieniu82** [comment]
`You could have found this by yourself by just investing a little more time and browsing trough the issue tracker for the open and closed issues ...`
Not sure about @shadowdavis but I did follow all the suggestions from other issues (including the entity name check and placing vendor attribute in the card config) and I still encounter exact same problem.

**Comment by Tamsy** [comment]
> `You could have found this by yourself by just investing a little more time and browsing trough the issue tracker for the open and closed issues ...` Not sure about @shadowdavis but I did follow all the suggestions from other issues (including the entity name check and placing vendor attribute in the card config) and I still encounter exact same problem.

Are you sure you have changed the original name of the entity for the vacuum device itself adjusting it to the name of the (new) sensors through the HA web interface? At the beginning I had some difficulties with this too.

Settings → Integrations → Xiaomi Miio → Roborock Device → Device → My Device

(was roborock.vacuum.s5e, changed it to Roborock S5 Max (unten) <-- name I assigned when 1st installed the vaccum

Additionally activating all as per default deactivated entities (sensors) for the vacuums, all labels are now showing correctly at the lovelace-xiaomi-vacuum-cards with v4.4.0.

**Comment by Bieniu82** [comment]
`Are you sure you have changed the original name of the entity for the vacuum device itself adjusting it to the name of the (new) sensors through the HA web interface? At the beginning I had some difficulties with this too.`

Yep. It didn't help. Then I removed entirely the Xiaomi Miio integration and reinstalled it (choosing no-cloud option).
Having it reinstalled - the new entity has shown up as _vacuum.roborock_vacuum_s5e_, that is exact same prefix as all the sensors have. I checked the card config in lovelace yaml and it looks consistent. Also I disabled and enabled the sensors back (some of them were inactive after reinstallation). I tried downgrading the card to 4.3.0 and back to 4.4.0, did several cache clearing and gave up. Can't see the sensor values at the right hand side and icons of the buttons ad the bottom (icons are there as with my mouse I can hoover over them but icons are not displayed).

My entities:
![entities](https://user-images.githubusercontent.com/53428288/141154018-48f1f8f2-2a83-4953-96eb-be9aef1ea784.JPG)

My card config:
![card](https://user-images.githubusercontent.com/53428288/141154302-c402a617-39fc-404a-8889-e8cef8211241.JPG)

My card itself:
![card_issue](https://user-images.githubusercontent.com/53428288/141154426-ae61f50b-f9bc-4b76-8027-7d6703685967.JPG)
[env_team_work.docx](https://github.com/benct/lovelace-xiaomi-vacuum-card/files/7514398/env_team_work.docx)
[faktura_3-11-2021-SKLEP.pdf](https://github.com/benct/lovelace-xiaomi-vacuum-card/files/7514399/faktura_3-11-2021-SKLEP.pdf)

**Comment by shadowdavis** [comment]
> `Are you sure you have changed the original name of the entity for the vacuum device itself adjusting it to the name of the (new) sensors through the HA web interface? At the beginning I had some difficulties with this too.`
> 
> Yep. It didn't help. Then I removed entirely the Xiaomi Miio integration and reinstalled it (choosing no-cloud option). Having it reinstalled - the new entity has shown up as _vacuum.roborock_vacuum_s5e_, that is exact same prefix as all the sensors have. I checked the card config in lovelace yaml and it looks consistent. Also I disabled and enabled the sensors back (some of them were inactive after reinstallation). I tried downgrading the card to 4.3.0 and back to 4.4.0, did several cache clearing and gave up. Can't see the sensor values at the right hand side and icons of the buttons ad the bottom (icons are there as with my mouse I can hoover over them but icons are not displayed).
> 
> My entities: ![entities](https://user-images.githubusercontent.com/53428288/141154018-48f1f8f2-2a83-4953-96eb-be9aef1ea784.JPG)
> 
> My card config: ![card](https://user-images.githubusercontent.com/53428288/141154302-c402a617-39fc-404a-8889-e8cef8211241.JPG)
> 
> My card itself: ![card_issue](https://user-images.githubusercontent.com/53428288/141154426-ae61f50b-f9bc-4b76-8027-7d6703685967.JPG)


I also browsed other closed issues, but either I can’t understand them or I still can’t solve them.
@Bieniu82 
I have the same problem as you，So I reinstalled v4.2.0 and everything is ok now.
Wait for the next update to see if everything is normal....

**Comment by Bieniu82** [comment]
update:
having upgraded HACS to 1.17.2 - the card works well, both sensors on the right hand side as well as the bottom panel icons are visible now

**Comment by shadowdavis** [comment]
> update:
> having upgraded HACS to 1.17.2 - the card works well, both sensors on the right hand side as well as the bottom panel icons are visible now

thanks！
but i tried to  upgrade hacs to 1.17.2, but the v4.4.0 version
Simple Vacuum Card still cannot display buttons and sensors, so I downgraded to 4.2.0 again...

**Comment by shadowdavis** [comment]
> update:
> having upgraded HACS to 1.17.2 - the card works well, both sensors on the right hand side as well as the bottom panel icons are visible now

I tried to update HA to 2021.11.4, and updated this card to v4.4.0, the button appeared, and it worked normally, but the sensor on the right was unavailable. .

**Comment by perseus177** [comment]
<html><body>


Software | Version
-- | --
Home Assistant | core-2021.12.7
 lovelace-xiaomi-vacuum-card | 4.4.0


</body>
</html>

I see buttons but, Sensors are unavailable 

![image](https://user-images.githubusercontent.com/25415840/147937384-3eae83bd-c0c0-4100-a882-68f95360e1d0.png)

![image](https://user-images.githubusercontent.com/25415840/147938026-32a6daec-7a17-49e5-8787-5de1d10b85f8.png)

**Comment by achagaev** [comment]
> > update:
> > having upgraded HACS to 1.17.2 - the card works well, both sensors on the right hand side as well as the bottom panel icons are visible now
> 
> I tried to update HA to 2021.11.4, and updated this card to v4.4.0, the button appeared, and it worked normally, but the sensor on the right was unavailable. .

I tried with HA=2021.12.7, HACS=1.18.0 and manually installed card=4.4.0 and it didn't work (previously it was OK).
It started working as soon as I installed card via HACS.
