### ISSUE TITLE
Sensors are unavailable

### ISSUE THREAD

**Issue by perseus177** [benct/lovelace-xiaomi-vacuum-card#92]
<html><body>

Software | Version
-- | --
Home Assistant | core-2021.12.7
lovelace-xiaomi-vacuum-card | 4.4.0
HACS  | 1.18.0

</body>
</html>

UI Lovelace
```
      - type: custom:xiaomi-vacuum-card    
        entity: vacuum.xiaomi_vacuum_cleaner
        image: /local/img/vacuum.png
        name: Robo
        vendor: xiaomi
```

I see buttons but, Sensors are unavailable 

![image](https://user-images.githubusercontent.com/25415840/147937384-3eae83bd-c0c0-4100-a882-68f95360e1d0.png)

![image](https://user-images.githubusercontent.com/25415840/147938026-32a6daec-7a17-49e5-8787-5de1d10b85f8.png)

**Comment by achagaev** [comment]
It sounds similar to previous issue #91:
https://github.com/benct/lovelace-xiaomi-vacuum-card/issues/91

Try to check that all your entities mentioned in 'Diagnostic' part are in alignment with name of your device.
As example, you should have 'DnD end' like below:
sensor.roborock_vacuum_s5_dnd_end

**Comment by perseus177** [comment]
![Screenshot_20220103-191733_Home Assistant](https://user-images.githubusercontent.com/25415840/147965150-fae631b9-d30d-41f2-8791-c956f15920a7.jpg)
![Screenshot_20220103-191717_Home Assistant](https://user-images.githubusercontent.com/25415840/147965153-c47a71e9-6313-4e89-9d74-564f1be95b4c.jpg)

**Comment by perseus177** [comment]
I change side brush like you wrote, but still it is not working
![Screenshot_20220103-192244_Home Assistant](https://user-images.githubusercontent.com/25415840/147965649-d5467c0e-fc92-4b58-b9b3-7548e9892386.jpg)

**Comment by achagaev** [comment]
here is working solution on my environment:
https://github.com/benct/lovelace-xiaomi-vacuum-card/issues/91#issuecomment-1004204655
don't forget to clean cache before verification.

**Comment by perseus177** [comment]
Fixed, thanks

**Comment by perseus177** [comment]
@achagaev it is working on web-browser but it is not working in mobile application. I tried also reload application and also login/logout. But still it is not working

**Comment by achagaev** [comment]
check how to clean cache on your mobile app based on your OS and try it

**Comment by perseus177** [comment]
@achagaev  thanks, it helps 
How to clear cache: 
https://community.home-assistant.io/t/does-anyone-know-how-to-flush-android-app-cache-to-avoid-unexpected-frontend-version-in-hacs/281952
