### ISSUE TITLE
Option to 'light up' buttons

### ISSUE THREAD

**Issue by maikvitesse** [benct/lovelace-xiaomi-vacuum-card#94]
[enhancement]

Would be nice if there is an option to customize a button with a variable to 'light up' the button.

Example:
- I press the 'hallway' button
- button sends a command to the vacuum to clean the 'hallway'
- button 'lights up' until it's done cleaning thanks to an input-boolean i created

**Comment by benct** [comment]
This could be solved with [card-mod](https://github.com/thomasloven/lovelace-card-mod), by setting some styles on the button(s) based on your input boolean.
