### ISSUE TITLE
vacumcleaner

### ISSUE THREAD

**Issue by Worgak** [benct/lovelace-xiaomi-vacuum-card#97]
I can't connect one xiaomi vacuum cleaner vacuum cleaner V1, one connects me without problems the other I can't connect. he's writing me this message

Logger: homeassistant.config_entries
Source: config_entries.py:344
First occurred: 14:29:13 (2 occurrences)
Last logged: 14:32:40

Config entry 'Darebak' for xiaomi_miio integration not ready yet; Retrying in background
Config entry 'rockrobo.vacuum.v1' for xiaomi_miio integration not ready yet; Retrying in background

**Comment by benct** [comment]
Sorry, that must be a problem with the [integration](https://github.com/home-assistant/core/tree/dev/homeassistant/components/xiaomi_miio), not with this card.
