### ISSUE TITLE
Deebot not reading states

### ISSUE THREAD

**Issue by Vendo232** [benct/lovelace-xiaomi-vacuum-card#98]
using latest HA and HACS integration
Home Assistant 2022.2.5
integration: 4.4

![image](https://user-images.githubusercontent.com/44098230/153478882-26507224-3c32-408e-b9c3-b364acb79e1c.png)

**Comment by benct** [comment]
Check that you have enabled the necessary integration sensors and that the sensor naming matches the required setup. See [here](https://github.com/benct/lovelace-xiaomi-vacuum-card/issues/84#issuecomment-962684848) for more info.
