### ISSUE TITLE
Broken dropdown on HA 2021.3.x

### ISSUE THREAD

**Issue by LEJOUI** [benct/lovelace-xiaomi-vacuum-card#99]
Hi,

Updated to the latest version (beta) of HA, 2021.3.0.b4.
Now the card looks weird. Not sure if it’s HA related or a beta issue though. 

![5F348D8D-9A53-49DE-8CB0-A7DC5E25FAEB](https://user-images.githubusercontent.com/13658422/156050439-bf27c4a0-a9b2-4855-a8e8-d555a56a1a4e.png)

**Comment by breti** [comment]
Related to the UI upgrade, I'd guess. https://www.home-assistant.io/blog/2022/03/02/release-20223/#ui-upgrades

**Comment by joselcaguilar** [comment]
> Related to the UI upgrade, I'd guess. https://www.home-assistant.io/blog/2022/03/02/release-20223/#ui-upgrades

Yup, it's also in [mini-media-player](https://github.com/kalkih/mini-media-player) plugin due to `paper-menu-button` and `paper-listbox`, maybe the [issue thread](https://github.com/kalkih/mini-media-player/issues/606) might be helpful for this one too.

**Comment by LEJOUI** [comment]
Might be already known because of answers above, but here's the blogpost [https://developers.home-assistant.io/blog/2022/02/18/paper-elements/](https://developers.home-assistant.io/blog/2022/02/18/paper-elements/)

**Comment by lfrlucas** [comment]
I experienced the same issue after upgrading Home Assistant to 2022.3

**Comment by htmltiger** [comment]
this may help
https://github.com/benct/lovelace-xiaomi-vacuum-card/pull/100

here is the fork
https://github.com/htmltiger/lovelace-xiaomi-vacuum-card

**Comment by silviudc** [comment]
Is the fork working for you guys? I installed it, rebooted HA, cleared the browser cache and still seeing this 
![image](https://user-images.githubusercontent.com/17740184/156642575-97a0c0b3-165f-4197-ac5f-f8384fdfdb6c.png)

**Comment by htmltiger** [comment]
This is from old cache or not installed correctly.

check this file is same from the new download
/config/www/community/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
and delete any .gz file from the same folder

or 

remove existing addon and  add custom repo in hacs as https://github.com/htmltiger/lovelace-xiaomi-vacuum-card

**Comment by supergroover** [comment]
It's not working here too, buy maybe i'm doing something wrong.

**Comment by 3ative** [comment]
Thanks @htmltiger - it's working here too 👍
Downloaded, replaced, deleted .gz and cleared cache 

We just need the HA devs to fix the **HUGE** Drop-Down boxes now _LMAO_
![image](https://user-images.githubusercontent.com/51385971/156676985-1267540d-6afb-4300-acb6-5656082f6eaf.png)

**Comment by benct** [comment]
Should be fixed in version `4.5.0` and working like before (no huge select/dropdown box).

Clear cache, refresh, etc..

**Comment by LEJOUI** [comment]
Works here! Great work, closing this issue.
